[versions]
androidx-annotation = "1.9.1"
androidx-test-junit = "1.3.0"
antlr-kotlin = "1.0.8"
circuit = "0.31.0"
coil = "3.3.0"
colormath = "3.6.1"
compottie = "2.0.2"
fluidLocale = "0.13.0"
gtoSupport = "4.5.0"
jvm = "21"
kotlin = "2.3.0"
kotlinCoroutines = "1.10.2"
kustomExport = "0.8.2"
goncalossilvaResources = "0.14.1"
ktlint = "1.8.0"
ktlintGradle = "14.0.1"
napier = "2.6.1"
npmPublish = "3.5.3"
okio = "3.16.4"
robolectric = "4.15.1"

[libraries]
android-gradle = "com.android.tools.build:gradle:8.13.2"
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-compose-ui-test-manifest = "androidx.compose.ui:ui-test-manifest:1.9.5"
androidx-graphics-shapes = "androidx.graphics:graphics-shapes:1.1.0"
androidx-lifecycle-runtime-compose = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose:2.9.6"
androidx-lifecycle-testing = "androidx.lifecycle:lifecycle-runtime-testing:2.10.0"
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
antlr-kotlin-gradle = { module = "com.strumenta:antlr-kotlin-gradle-plugin", version.ref = "antlr-kotlin" }
antlr-kotlin-runtime = { module = "com.strumenta:antlr-kotlin-runtime", version.ref = "antlr-kotlin" }
circuit-runtime = { module = "com.slack.circuit:circuit-runtime", version.ref = "circuit" }
circuit-test = { module = "com.slack.circuit:circuit-test", version.ref = "circuit" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-test = { module = "io.coil-kt.coil3:coil-test", version.ref = "coil" }
colormath = { module = "com.github.ajalt.colormath:colormath", version.ref = "colormath" }
colormath-android-colorint = { module = "com.github.ajalt.colormath:colormath-ext-android-colorint", version.ref = "colormath" }
colormath-jetpack-compose = { module = "com.github.ajalt.colormath:colormath-ext-jetpack-compose", version.ref = "colormath" }
compose-media-player = "network.chaintech:compose-multiplatform-media-player:1.0.50"
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
compottie-dot = { module = "io.github.alexzhirkevich:compottie-dot", version.ref = "compottie" }
fluidLocale = { module = "io.fluidsonic.locale:fluid-locale", version.ref = "fluidLocale" }
goncalossilvaResources = { module = "com.goncalossilva:resources", version.ref = "goncalossilvaResources" }
gtoSupport-androidx-lifecycle = { module = "org.ccci.gto.android:gto-support-androidx-lifecycle", version.ref = "gtoSupport" }
gtoSupport-androidx-test-junit = { module = "org.ccci.gto.android:gto-support-androidx-test-junit", version.ref = "gtoSupport" }
gtoSupport-compose = { module = "org.ccci.gto.android:gto-support-compose", version.ref = "gtoSupport" }
gtoSupport-fluidsonic-locale = { module = "org.ccci.gto.android:gto-support-fluidsonic-locale", version.ref = "gtoSupport" }
gtoSupport-okio = { module = "org.ccci.gto.android:gto-support-okio", version.ref = "gtoSupport" }
gtoSupport-parcelize = { module = "org.ccci.gto.android:gto-support-parcelize", version.ref = "gtoSupport" }
kermit = "co.touchlab:kermit:2.0.8"
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-immutable-collections = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.4.0"
kotlin-kover-gradle = "org.jetbrains.kotlinx:kover-gradle-plugin:0.9.4"
ktlint-gradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintGradle" }
ktlint-rules-compose = "io.nlopez.compose.rules:ktlint:0.5.3"
kustomExport = { module = "deezer.kustomexport:lib", version.ref = "kustomExport" }
kustomExport-compiler = { module = "deezer.kustomexport:compiler", version.ref = "kustomExport" }
kustomExport-coroutines = { module = "deezer.kustomexport:lib-coroutines", version.ref = "kustomExport" }
materialColorUtilities = "org.cru.mobile.fork.material-color-utilities:material-color-utilities:0.2.0_75"
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
testparameterinjector = "com.google.testparameterinjector:test-parameter-injector:1.20"
turbine = "app.cash.turbine:turbine:1.2.1"

# HACK: dependencies used to trigger renovate upgrades
ktlint = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }

[bundles]
android-test-framework = ["androidx-test-junit", "robolectric"]
common-test-framework = ["kotlin-coroutines-test"]
ktlint-rulesets = ["ktlint-rules-compose"]

[plugins]
compose = { id = "org.jetbrains.compose", version = "1.9.3" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
goncalossilvaResources = { id = "com.goncalossilva.resources", version.ref = "goncalossilvaResources" }
grgit = { id = "org.ajoberstar.grgit", version = "5.3.3" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.4" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
npm-publish = { id = "dev.petuska.npm.publish", version.ref = "npmPublish" }
paparazzi = { id = "app.cash.paparazzi", version = "2.0.0-alpha02" }
